// Generated by `wrangler types --env-interface CloudflareEnv`.
// QDRANT_URL and QDRANT_API_KEY are secret bindings and are intentionally
// declared by name only; no secret value is committed.
declare namespace Cloudflare {
  interface Env {
    AI: Ai;
    EXECUTION_ENABLED: "false" | "true";
    QDRANT_COLLECTION: "llm_wiki_m23_pilot_bge_m3_1024";
    QDRANT_VECTOR_NAME: "default";
    EMBEDDING_MODEL: "@cf/baai/bge-m3";
    MAX_SECTIONS_PER_MESSAGE: "25";
    MAX_SECTIONS_PER_RUN: "500";
    MAX_ESTIMATED_USD_PER_RUN: "0.5";
    QDRANT_URL: string;
    QDRANT_API_KEY: string;
  }
}
interface CloudflareEnv extends Cloudflare.Env {}
