// Generated by `wrangler types --env-interface CloudflareEnv` and completed
// with secret binding names only. No secret value is committed.
declare namespace Cloudflare {
  interface Env {
    AI: Ai;
    CANDIDATE_RUNTIME_ENABLED: "false" | "true";
    SHADOW_SEMANTIC_ENABLED: "false" | "true";
    QDRANT_COLLECTION: "llm_wiki_m23_pilot_bge_m3_1024";
    QDRANT_VECTOR_NAME: "default";
    EMBEDDING_MODEL: "@cf/baai/bge-m3";
    ACCESS_TEAM_DOMAIN: string;
    ACCESS_POLICY_AUD: string;
    MAX_QUERY_CHARS: "2000";
    MAX_TOP_K: "20";
    QDRANT_TIMEOUT_MS: "5000";
    QDRANT_URL: string;
    QDRANT_API_KEY: string;
  }
}
interface CloudflareEnv extends Cloudflare.Env {}
